apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mysql-replica
  name: mysql-replica
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3306
  clusterIP: None
  selector:
    io.kompose.service: mysql-replica
